dist: bionic
language: php
addons:
  apt:
    packages:
    - libengine-gost-openssl1.1

before_install:
    - sudo bash tests/.configure-gost-openssl.sh

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

install:
  - travis_retry composer self-update
  - travis_retry composer --version
  - travis_retry composer update --prefer-dist --no-interaction

script:
  - chmod 000 tests/_data/non_readable_file
  - php vendor/codeception/codeception/codecept run
